### ISSUE TITLE
Why the day_index must be smaller than 12?

### ISSUE THREAD

**Issue by BEbillionaireUSD** [andreaskuster/reproducing-serverless-in-the-wild#12]
Thanks very much to your team for this impressive work!

I'm just wondering why the day_index must be 1...12. What if I want to reproduce the result of the paper, i.e., using the first 12 days for training and testing the performance with the last two days? In this case, how should I set the parameters in `simulate.py`?

Thanks in advance and looking forward to your reply!

**Comment by andreaskuster** [comment]
Hi @BEbillionaireUSD 

Thank you for your interest in our project. 

The reason for excluding day 13 and 14 in our study was the lack of the `app_memory` field in the dataset for those days. YOu can find the remark here: https://github.com/andreaskuster/reproducing-serverless-in-the-wild/blob/main/model/dataset.py#L64

Depending on what you want to simulate (if `app_memory` is not required), you can still execute the mentioned scenario above.

You are welcome to submit a pull request with any improvements or enhancements to the code base.

**Comment by BEbillionaireUSD** [comment]
Thanks very much for your prompt reply! My question has been well answered and I will close this issue. I really appreciate your reply!
